<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Monday, April 1, 2024 10:23:45 AM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">testing</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x000001D6177DDFB0&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\working\xml_to_layer.py", line 236, in &lt;module&gt;
    main()
  File "D:\working\xml_to_layer.py", line 195, in main
    pls_cadd_list = pls_cadd_comparison_table(xml_file)
  File "D:\working\xml_to_layer.py", line 105, in pls_cadd_comparison_table
    add_message(str(pls_cadd_list))
TypeError: 'xml.etree.ElementTree.Element' object is not callable
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Monday, April 1, 2024 10:23:56 AM (Elapsed Time: 10.90 seconds)</msg></messages>