<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, April 13, 2024 4:42:45 PM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">testing</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x0000022C13D82E30&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="0" type="0">getting arc pro list</msg><msg code="0" type="0">ETL.1840</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 382, in &lt;module&gt;
    main()
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 375, in main
    create_sections_feature_from_OH_conductor(dst_sections, dst_gdb, arc_pro_list, sr=xml_sr )
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 314, in create_sections_feature_from_OH_conductor
    [arcpy.Point(vertices_to_keep[counter_1]), arcpy.Point(vertices_to_keep[counter_1+1])]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\mixins.py", line 1101, in __init__
    setattr(self, attr, value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\_base.py", line 109, in _set
    return setattr(self._arc_object, attr_name, cval(val))
RuntimeError: Point: Input value is not numeric
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Saturday, April 13, 2024 4:43:32 PM (Elapsed Time: 46.65 seconds)</msg></messages>